#!/usr/bin/env bash
# Build addon/RuleData.lua from sensitive/<category>.txt wordlists.
# Output is sorted by hash for stable diffs and uses the newest source file's
# mtime as generated_at, so re-running with no input change produces no diff.
#
# Missing input files are skipped with a note (not errors). Hash collisions
# between two distinct normalized inputs are fatal — fix the inputs.
#
# Usage: ./scripts/build-rules.sh

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SENSITIVE_DIR="$PROJECT_ROOT/sensitive"
OUTPUT_FILE="$PROJECT_ROOT/addon/RuleData.lua"

CATEGORIES=(
    "identity_attack"
    "slur"
    "role_attack"
    "harassment"
    "harm_invocation"
    "general_hostility"
)

python3 - "$SENSITIVE_DIR" "$OUTPUT_FILE" "${CATEGORIES[@]}" <<'PY'
import datetime
import os
import sys

sensitive_dir = sys.argv[1]
output_file   = sys.argv[2]
categories    = sys.argv[3:]

FNV_OFFSET = 2166136261
FNV_PRIME  = 16777619
MOD32      = 2 ** 32

def fnv1a(s: str) -> int:
    h = FNV_OFFSET
    for b in s.encode("utf-8"):
        h ^= b
        h = (h * FNV_PRIME) % MOD32
    return h

PUNCT = set('.,!?;:\'"()[]{}<>/\\|')
LEET = {
    "0": "o", "1": "i", "3": "e", "4": "a",
    "5": "s", "7": "t", "8": "b", "@": "a", "$": "s",
}

def normalize(token: str) -> str:
    s = token.lower()
    s = "".join(c for c in s if c not in PUNCT)
    out = []
    i = 0
    while i < len(s):
        c = s[i]
        j = i
        while j < len(s) and s[j] == c:
            j += 1
        run = j - i
        if run >= 3:
            out.append(c)
        else:
            out.append(c * run)
        i = j
    s = "".join(out)
    s = "".join(LEET.get(c, c) for c in s)
    s = "".join(c for c in s if not c.isspace())
    return s

# Parity check with addon/Hash.lua — divergence here means the addon's
# self-test would also fail at load. Catch it at build time too.
assert fnv1a("")     == 2166136261
assert fnv1a("a")    == 3826002220
assert fnv1a("test") == 2949673445

words = {}        # hash -> (category, severity, normalized_input)
collisions = []   # (hash, normalized_a, normalized_b)
mtimes = []
seen_categories = set()

for cat in categories:
    path = os.path.join(sensitive_dir, cat + ".txt")
    if not os.path.exists(path):
        print(f"  skipped: {cat}.txt not found")
        continue
    mtimes.append(os.path.getmtime(path))
    with open(path, "r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            if ":" in line:
                word, sev_str = line.rsplit(":", 1)
                try:
                    severity = int(sev_str)
                except ValueError:
                    print(f"  warning: bad severity in {cat}.txt: {raw_line.rstrip()!r}")
                    continue
            else:
                word = line
                severity = 5
            word = word.strip()
            if not word:
                continue
            normalized = normalize(word)
            if not normalized:
                print(f"  warning: empty normalization in {cat}.txt: {raw_line.rstrip()!r}")
                continue
            h = fnv1a(normalized)
            if h in words:
                existing_cat, existing_sev, existing_norm = words[h]
                if existing_norm != normalized:
                    collisions.append((h, existing_norm, normalized))
                    continue
                # Same normalized form across categories: keep highest severity,
                # don't switch category silently.
                if severity > existing_sev:
                    words[h] = (existing_cat, severity, existing_norm)
                continue
            words[h] = (cat, severity, normalized)
            seen_categories.add(cat)

if collisions:
    print("ERROR: hash collision(s) detected:")
    for h, a, b in collisions:
        print(f"  hash {h}: {a!r}  vs  {b!r}")
    print("Resolve by adjusting normalization or removing one of the inputs.")
    sys.exit(1)

if mtimes:
    ts = datetime.datetime.fromtimestamp(max(mtimes), datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
else:
    ts = "1970-01-01T00:00:00Z"

with open(output_file, "w", encoding="utf-8") as f:
    f.write("-- AUTO-GENERATED by scripts/build-rules.sh -- do not edit by hand.\n")
    f.write("-- To regenerate: ./scripts/build-rules.sh\n\n")
    f.write("local _, ns = ...\n\n")
    f.write("ns.RuleData = {\n")
    f.write('    hash_version = "fnv1a-32",\n')
    f.write('    normalization_version = "v1",\n')
    f.write(f'    generated_at = "{ts}",\n\n')
    f.write("    -- Single-word rules: hash -> {category, severity}\n")
    f.write("    words = {\n")
    for h in sorted(words.keys()):
        cat, sev, _ = words[h]
        f.write(f'        [{h}] = {{category = "{cat}", severity = {sev}}},\n')
    f.write("    },\n\n")
    f.write("    -- Multi-word phrase rules. Empty in Sprint 1; structure documented for Sprint 2.\n")
    f.write("    -- Per entry: {tokens = {hash1, hash2, ...}, max_distance = N, category = \"...\", severity = N}\n")
    f.write("    -- Phrase tokens are normalized at build time before hashing, identical to runtime.\n")
    f.write("    phrases = {},\n\n")
    f.write("    stats = {\n")
    f.write(f"        word_count = {len(words)},\n")
    f.write("        phrase_count = 0,\n")
    f.write("    },\n")
    f.write("}\n")

print(f"Generated RuleData.lua: {len(words)} rules across {len(seen_categories)} categories")
PY
