-- AUTO-GENERATED by scripts/build-rules.sh -- do not edit by hand.
-- To regenerate: ./scripts/build-rules.sh

local _, ns = ...

ns.RuleData = {
    hash_version = "fnv1a-32",
    normalization_version = "v1",
    generated_at = "2026-04-28T22:09:51Z",

    -- Single-word rules: hash -> {category, severity}
    words = {
        [304217282] = {category = "general_hostility", severity = 6},
        [560463001] = {category = "slur", severity = 9},
        [562110366] = {category = "role_attack", severity = 5},
        [627573477] = {category = "slur", severity = 8},
        [859193583] = {category = "harassment", severity = 6},
        [960624768] = {category = "identity_attack", severity = 7},
        [1027735244] = {category = "identity_attack", severity = 5},
        [1153813185] = {category = "identity_attack", severity = 5},
        [1156727645] = {category = "slur", severity = 6},
        [1360707206] = {category = "role_attack", severity = 5},
        [1427817682] = {category = "role_attack", severity = 5},
        [1813726278] = {category = "harassment", severity = 5},
        [2006727794] = {category = "general_hostility", severity = 7},
        [2018046116] = {category = "harm_invocation", severity = 10},
        [2236421558] = {category = "harassment", severity = 8},
        [2249816622] = {category = "role_attack", severity = 7},
        [2316927098] = {category = "role_attack", severity = 4},
        [2334128933] = {category = "harm_invocation", severity = 8},
        [2411840088] = {category = "identity_attack", severity = 6},
        [2478950564] = {category = "identity_attack", severity = 7},
        [2550119336] = {category = "harm_invocation", severity = 9},
        [2617229812] = {category = "harm_invocation", severity = 5},
        [2745473939] = {category = "slur", severity = 5},
        [2812584415] = {category = "slur", severity = 8},
        [2829362034] = {category = "slur", severity = 5},
        [2926798768] = {category = "harm_invocation", severity = 9},
        [3275340947] = {category = "general_hostility", severity = 5},
        [3512823396] = {category = "identity_attack", severity = 8},
        [3540400168] = {category = "general_hostility", severity = 7},
        [3607510644] = {category = "general_hostility", severity = 6},
        [3720681534] = {category = "harassment", severity = 7},
        [3787792010] = {category = "harassment", severity = 5},
        [4205249671] = {category = "role_attack", severity = 6},
        [4225173946] = {category = "slur", severity = 7},
    },

    -- Multi-word phrase rules. Empty in Sprint 1; structure documented for Sprint 2.
    -- Per entry: {tokens = {hash1, hash2, ...}, max_distance = N, category = "...", severity = N}
    -- Phrase tokens are normalized at build time before hashing, identical to runtime.
    phrases = {},

    stats = {
        word_count = 34,
        phrase_count = 0,
    },
}
